import React, { createContext, useContext, useState } from 'react'

function loadJSON(key, fallback) {
  try { return JSON.parse(localStorage.getItem(key)) ?? fallback }
  catch { return fallback }
}
function saveJSON(key, val) {
  try { localStorage.setItem(key, JSON.stringify(val)) } catch {}
}

const TRANSLATIONS = {
  english: {
    home: 'Home', bible: 'Bible', quizzes: 'Quizzes', askAI: 'Ask AI',
    dashboard: 'Dashboard', didYouKnow: 'Did You Know', games: 'Games',
    community: 'Community', settings: 'Settings', startStudying: 'Start Studying',
    settingsTitle: 'Settings', settingsSubtitle: 'Personalise your ScriptureHub experience',
    appearance: 'Appearance', reading: 'Reading', studyQuizzes: 'Study & Quizzes',
    features: 'Features', accountData: 'Account & Data', about: 'About',
    saveSettings: 'Save Settings', saved: '✅ Saved!',
    darkMode: 'Dark Mode', darkModeDesc: 'Switch between light and dark themes',
    accentColour: 'Accent Colour', accentColourDesc: 'Choose your personal highlight colour',
    fontSize: 'Font Size', fontSizeDesc: 'Adjust the reading text size across the site',
    fontStyle: 'Font Style', fontStyleDesc: 'Choose your preferred reading font',
    compactMode: 'Compact Mode', compactModeDesc: 'Reduce spacing for a denser layout',
    animations: 'Animations', animationsDesc: 'Enable smooth transitions and hover effects',
    language: 'Language', languageDesc: 'Choose your preferred display language',
    defaultBible: 'Default Bible Translation', defaultBibleDesc: 'Choose which translation opens by default',
    readingGoal: 'Daily Reading Goal', readingGoalDesc: 'Set how many chapters you aim to read each day',
    chapter: 'chapter', chapters: 'chapters',
    verseOfDay: 'Verse of the Day', verseOfDayDesc: 'Show a featured verse on your dashboard',
    autoPlay: 'Auto-Play Audio', autoPlayDesc: 'Automatically play audio when opening a chapter',
    quizDifficulty: 'Quiz Difficulty', quizDifficultyDesc: 'Set the default difficulty for quizzes',
    showStreak: 'Show Streak Counter', showStreakDesc: 'Display your daily study streak',
    notifications: 'Study Reminders', notificationsDesc: 'Receive reminders to maintain your streak',
    soundEffects: 'Sound Effects', soundEffectsDesc: 'Play sounds on quiz answers and badge unlocks',
    floatingChat: 'Floating AI Chat', floatingChatDesc: 'Show the floating AI assistant on all pages',
    progressSummary: 'Your Progress Summary', progressDesc: 'A snapshot of your ScriptureHub journey',
    exportData: 'Export My Data', exportDesc: 'Download all your progress as a JSON file',
    downloadBtn: '📥 Download My Data',
    resetSettings: 'Reset Settings', resetDesc: 'Restore all settings to default values',
    resetBtn: '🔄 Reset to Defaults',
    clearData: 'Clear All Data', clearDesc: 'Permanently delete all your progress. Cannot be undone.',
    clearBtn: '🗑️ Clear All Data', reset: 'Reset',
    communityTitle: 'The Living Stone Wall',
    communitySubtitle: "Carve your faith, earn rare badges, walk the Prophet's Path, and discover hidden treasures.",
    stoneWall: '🪨 Stone Wall', treasureChest: '🏆 Treasure Chest',
    prophetPath: "🕊️ Prophet's Path", easterEggs: '🔍 Easter Eggs',
    carveStone: '✍️ Carve Your Stone', carveBtn: '🪨 Carve My Stone',
    carvedBtn: '✅ Stone Carved!', wallTitle: '🏛️ The Wall of Remembrance',
    stones: 'Stones', amen: 'Amen', amenDone: 'Amen ✓',
    welcomeBack: 'Welcome Back', yourProgress: 'Your Progress',
    beginner: 'Beginner', medium: 'Medium', hard: 'Hard', scholar: 'Scholar',
    small: 'Small', large: 'Large', extraLarge: 'Extra Large',
  },

  french: {
    home: 'Accueil', bible: 'Bible', quizzes: 'Quiz', askAI: "Demander à l'IA",
    dashboard: 'Tableau de bord', didYouKnow: 'Le saviez-vous', games: 'Jeux',
    community: 'Communauté', settings: 'Paramètres', startStudying: 'Commencer à étudier',
    settingsTitle: 'Paramètres', settingsSubtitle: 'Personnalisez votre expérience ScriptureHub',
    appearance: 'Apparence', reading: 'Lecture', studyQuizzes: 'Étude et Quiz',
    features: 'Fonctionnalités', accountData: 'Compte et Données', about: 'À propos',
    saveSettings: 'Enregistrer', saved: '✅ Enregistré!',
    darkMode: 'Mode Sombre', darkModeDesc: 'Basculer entre les thèmes clair et sombre',
    accentColour: "Couleur d'Accent", accentColourDesc: 'Choisissez votre couleur personnelle',
    fontSize: 'Taille de Police', fontSizeDesc: 'Ajustez la taille du texte de lecture',
    fontStyle: 'Style de Police', fontStyleDesc: 'Choisissez votre police de lecture préférée',
    compactMode: 'Mode Compact', compactModeDesc: "Réduire l'espacement pour une mise en page plus dense",
    animations: 'Animations', animationsDesc: 'Activer les transitions fluides',
    language: 'Langue', languageDesc: "Choisissez votre langue d'affichage préférée",
    defaultBible: 'Traduction Bible par Défaut', defaultBibleDesc: "Choisissez la traduction qui s'ouvre par défaut",
    readingGoal: 'Objectif de Lecture Quotidien', readingGoalDesc: 'Définissez combien de chapitres vous souhaitez lire',
    chapter: 'chapitre', chapters: 'chapitres',
    verseOfDay: 'Verset du Jour', verseOfDayDesc: 'Afficher un verset en vedette sur votre tableau de bord',
    autoPlay: 'Lecture Audio Automatique', autoPlayDesc: "Lire automatiquement l'audio à l'ouverture d'un chapitre",
    quizDifficulty: 'Difficulté du Quiz', quizDifficultyDesc: 'Définir la difficulté par défaut des quiz',
    showStreak: 'Afficher le Compteur de Série', showStreakDesc: "Afficher votre série d'études quotidiennes",
    notifications: "Rappels d'Étude", notificationsDesc: 'Recevoir des rappels pour maintenir votre série',
    soundEffects: 'Effets Sonores', soundEffectsDesc: 'Jouer des sons sur les réponses aux quiz',
    floatingChat: 'Chat IA Flottant', floatingChatDesc: "Afficher l'assistant IA flottant sur toutes les pages",
    progressSummary: 'Résumé de vos Progrès', progressDesc: 'Un aperçu de votre parcours ScriptureHub',
    exportData: 'Exporter mes Données', exportDesc: 'Télécharger tous vos progrès en fichier JSON',
    downloadBtn: '📥 Télécharger mes Données',
    resetSettings: 'Réinitialiser les Paramètres', resetDesc: 'Restaurer tous les paramètres par défaut',
    resetBtn: '🔄 Réinitialiser',
    clearData: 'Effacer Toutes les Données', clearDesc: 'Supprimer définitivement tous vos progrès.',
    clearBtn: '🗑️ Effacer Tout', reset: 'Réinitialiser',
    communityTitle: 'Le Mur de Pierre Vivant',
    communitySubtitle: 'Gravez votre foi, gagnez des badges, marchez sur le Chemin du Prophète.',
    stoneWall: '🪨 Mur de Pierre', treasureChest: '🏆 Coffre au Trésor',
    prophetPath: '🕊️ Chemin du Prophète', easterEggs: '🔍 Œufs de Pâques',
    carveStone: '✍️ Gravez Votre Pierre', carveBtn: '🪨 Graver ma Pierre',
    carvedBtn: '✅ Pierre Gravée!', wallTitle: '🏛️ Le Mur du Souvenir',
    stones: 'Pierres', amen: 'Amen', amenDone: 'Amen ✓',
    welcomeBack: 'Bon Retour', yourProgress: 'Vos Progrès',
    beginner: 'Débutant', medium: 'Moyen', hard: 'Difficile', scholar: 'Érudit',
    small: 'Petit', large: 'Grand', extraLarge: 'Très Grand',
  },

  spanish: {
    home: 'Inicio', bible: 'Biblia', quizzes: 'Cuestionarios', askAI: 'Preguntar a la IA',
    dashboard: 'Panel', didYouKnow: '¿Sabías que', games: 'Juegos',
    community: 'Comunidad', settings: 'Configuración', startStudying: 'Empezar a Estudiar',
    settingsTitle: 'Configuración', settingsSubtitle: 'Personaliza tu experiencia en ScriptureHub',
    appearance: 'Apariencia', reading: 'Lectura', studyQuizzes: 'Estudio y Cuestionarios',
    features: 'Características', accountData: 'Cuenta y Datos', about: 'Acerca de',
    saveSettings: 'Guardar', saved: '✅ ¡Guardado!',
    darkMode: 'Modo Oscuro', darkModeDesc: 'Cambiar entre temas claro y oscuro',
    accentColour: 'Color de Acento', accentColourDesc: 'Elige tu color personal de resaltado',
    fontSize: 'Tamaño de Fuente', fontSizeDesc: 'Ajusta el tamaño del texto de lectura',
    fontStyle: 'Estilo de Fuente', fontStyleDesc: 'Elige tu fuente de lectura preferida',
    compactMode: 'Modo Compacto', compactModeDesc: 'Reducir el espaciado para un diseño más denso',
    animations: 'Animaciones', animationsDesc: 'Habilitar transiciones suaves',
    language: 'Idioma', languageDesc: 'Elige tu idioma de visualización preferido',
    defaultBible: 'Traducción Bíblica Predeterminada', defaultBibleDesc: 'Elige qué traducción se abre por defecto',
    readingGoal: 'Meta de Lectura Diaria', readingGoalDesc: 'Establece cuántos capítulos deseas leer cada día',
    chapter: 'capítulo', chapters: 'capítulos',
    verseOfDay: 'Versículo del Día', verseOfDayDesc: 'Mostrar un versículo destacado en tu panel',
    autoPlay: 'Reproducción Automática', autoPlayDesc: 'Reproducir audio automáticamente al abrir un capítulo',
    quizDifficulty: 'Dificultad del Cuestionario', quizDifficultyDesc: 'Establecer la dificultad predeterminada',
    showStreak: 'Mostrar Contador de Racha', showStreakDesc: 'Mostrar tu racha de estudio diario',
    notifications: 'Recordatorios de Estudio', notificationsDesc: 'Recibir recordatorios para mantener tu racha',
    soundEffects: 'Efectos de Sonido', soundEffectsDesc: 'Reproducir sonidos en respuestas de cuestionarios',
    floatingChat: 'Chat IA Flotante', floatingChatDesc: 'Mostrar el asistente IA flotante en todas las páginas',
    progressSummary: 'Resumen de tu Progreso', progressDesc: 'Un resumen de tu viaje en ScriptureHub',
    exportData: 'Exportar mis Datos', exportDesc: 'Descargar todo tu progreso como archivo JSON',
    downloadBtn: '📥 Descargar mis Datos',
    resetSettings: 'Restablecer Configuración', resetDesc: 'Restaurar todos los ajustes a sus valores predeterminados',
    resetBtn: '🔄 Restablecer',
    clearData: 'Borrar Todos los Datos', clearDesc: 'Eliminar permanentemente todo tu progreso.',
    clearBtn: '🗑️ Borrar Todo', reset: 'Restablecer',
    communityTitle: 'El Muro de Piedra Viviente',
    communitySubtitle: 'Graba tu fe, gana insignias, camina por el Camino del Profeta.',
    stoneWall: '🪨 Muro de Piedra', treasureChest: '🏆 Cofre del Tesoro',
    prophetPath: '🕊️ Camino del Profeta', easterEggs: '🔍 Huevos de Pascua',
    carveStone: '✍️ Graba tu Piedra', carveBtn: '🪨 Grabar mi Piedra',
    carvedBtn: '✅ ¡Piedra Grabada!', wallTitle: '🏛️ El Muro del Recuerdo',
    stones: 'Piedras', amen: 'Amén', amenDone: 'Amén ✓',
    welcomeBack: 'Bienvenido de Nuevo', yourProgress: 'Tu Progreso',
    beginner: 'Principiante', medium: 'Medio', hard: 'Difícil', scholar: 'Erudito',
    small: 'Pequeño', large: 'Grande', extraLarge: 'Extra Grande',
  },

  portuguese: {
    home: 'Início', bible: 'Bíblia', quizzes: 'Questionários', askAI: 'Perguntar à IA',
    dashboard: 'Painel', didYouKnow: 'Você Sabia', games: 'Jogos',
    community: 'Comunidade', settings: 'Configurações', startStudying: 'Começar a Estudar',
    settingsTitle: 'Configurações', settingsSubtitle: 'Personalize sua experiência no ScriptureHub',
    appearance: 'Aparência', reading: 'Leitura', studyQuizzes: 'Estudo e Questionários',
    features: 'Recursos', accountData: 'Conta e Dados', about: 'Sobre',
    saveSettings: 'Salvar', saved: '✅ Salvo!',
    darkMode: 'Modo Escuro', darkModeDesc: 'Alternar entre temas claro e escuro',
    accentColour: 'Cor de Destaque', accentColourDesc: 'Escolha sua cor pessoal de destaque',
    fontSize: 'Tamanho da Fonte', fontSizeDesc: 'Ajuste o tamanho do texto de leitura',
    fontStyle: 'Estilo de Fonte', fontStyleDesc: 'Escolha sua fonte de leitura preferida',
    compactMode: 'Modo Compacto', compactModeDesc: 'Reduzir espaçamento para layout mais denso',
    animations: 'Animações', animationsDesc: 'Ativar transições suaves',
    language: 'Idioma', languageDesc: 'Escolha seu idioma de exibição preferido',
    defaultBible: 'Tradução Bíblica Padrão', defaultBibleDesc: 'Escolha qual tradução abre por padrão',
    readingGoal: 'Meta de Leitura Diária', readingGoalDesc: 'Defina quantos capítulos deseja ler por dia',
    chapter: 'capítulo', chapters: 'capítulos',
    verseOfDay: 'Versículo do Dia', verseOfDayDesc: 'Mostrar versículo em destaque no painel',
    autoPlay: 'Reprodução Automática', autoPlayDesc: 'Reproduzir áudio automaticamente ao abrir capítulo',
    quizDifficulty: 'Dificuldade do Questionário', quizDifficultyDesc: 'Definir dificuldade padrão dos questionários',
    showStreak: 'Mostrar Contador de Sequência', showStreakDesc: 'Exibir sua sequência de estudo diário',
    notifications: 'Lembretes de Estudo', notificationsDesc: 'Receber lembretes para manter sua sequência',
    soundEffects: 'Efeitos Sonoros', soundEffectsDesc: 'Reproduzir sons nas respostas dos questionários',
    floatingChat: 'Chat IA Flutuante', floatingChatDesc: 'Mostrar assistente IA flutuante em todas as páginas',
    progressSummary: 'Resumo do seu Progresso', progressDesc: 'Um resumo da sua jornada no ScriptureHub',
    exportData: 'Exportar meus Dados', exportDesc: 'Baixar todo o seu progresso como arquivo JSON',
    downloadBtn: '📥 Baixar meus Dados',
    resetSettings: 'Redefinir Configurações', resetDesc: 'Restaurar todas as configurações padrão',
    resetBtn: '🔄 Redefinir',
    clearData: 'Limpar Todos os Dados', clearDesc: 'Excluir permanentemente todo o seu progresso.',
    clearBtn: '🗑️ Limpar Tudo', reset: 'Redefinir',
    communityTitle: 'O Muro de Pedra Vivo',
    communitySubtitle: 'Grave sua fé, ganhe emblemas, caminhe pelo Caminho do Profeta.',
    stoneWall: '🪨 Muro de Pedra', treasureChest: '🏆 Baú do Tesouro',
    prophetPath: '🕊️ Caminho do Profeta', easterEggs: '🔍 Ovos de Páscoa',
    carveStone: '✍️ Grave sua Pedra', carveBtn: '🪨 Gravar minha Pedra',
    carvedBtn: '✅ Pedra Gravada!', wallTitle: '🏛️ O Muro da Lembrança',
    stones: 'Pedras', amen: 'Amém', amenDone: 'Amém ✓',
    welcomeBack: 'Bem-vindo de Volta', yourProgress: 'Seu Progresso',
    beginner: 'Iniciante', medium: 'Médio', hard: 'Difícil', scholar: 'Estudioso',
    small: 'Pequeno', large: 'Grande', extraLarge: 'Extra Grande',
  },

  yoruba: {
    home: 'Ile', bible: 'Bibeli', quizzes: 'Idanwo', askAI: 'Beere lowo AI',
    dashboard: 'Pepe', didYouKnow: 'Se O Mo', games: 'Ere',
    community: 'Agbegbe', settings: 'Eto', startStudying: 'Bere Ikeko',
    settingsTitle: 'Eto', settingsSubtitle: 'Se akanse iriri ScriptureHub re',
    appearance: 'Irisi', reading: 'Kika', studyQuizzes: 'Ikeko ati Idanwo',
    features: 'Awon Eya', accountData: 'Akoolee ati Data', about: 'Nipa',
    saveSettings: 'Fi Pamo', saved: 'Ti Fi Pamo!',
    darkMode: 'Ipo Okunkun', darkModeDesc: 'Yipada laarin awon akori imole ati okunkun',
    accentColour: 'Awo Pataki', accentColourDesc: 'Yan awo ti ara eni re',
    fontSize: 'Iwon Leta', fontSizeDesc: 'Satunse iwon oro kika',
    fontStyle: 'Ara Leta', fontStyleDesc: 'Yan font kika ti o fe',
    compactMode: 'Ipo Iwapo', compactModeDesc: 'Din aaye sile fun eto ti o ni ipon diẹ sii',
    animations: 'Awon Ere idaraya', animationsDesc: 'Mu awon iyipada didan sisẹ',
    language: 'Ede', languageDesc: 'Yan ede ifihan ti o fe',
    defaultBible: 'Itumo Bibeli Aiyipada', defaultBibleDesc: 'Yan itumo ti o sii ni aiyipada',
    readingGoal: 'Ibi-afede Kika Ojoojumo', readingGoalDesc: 'Seto iye ori ti o fe ka lojoojumo',
    chapter: 'ori', chapters: 'awon ori',
    verseOfDay: 'Ese Ojo', verseOfDayDesc: 'Safihan ese ti a yan lori pepe re',
    autoPlay: 'Sisere Aifowowi', autoPlayDesc: 'Sere ohun aifowowi nigbati o sii ori kan',
    quizDifficulty: 'Isoro Idanwo', quizDifficultyDesc: 'Seto isoro aiyipada fun awon idanwo',
    showStreak: 'Safihan Kika Ila', showStreakDesc: 'Safihan ila ikeko ojoojumo re',
    notifications: 'Awon Iranti Ikeko', notificationsDesc: 'Gba awon iranti lati setoju ila re',
    soundEffects: 'Awon Ipa Ohun', soundEffectsDesc: 'Sere awon ohun lori awon idahun idanwo',
    floatingChat: 'Ibaraenisoro AI Lilefoofo', floatingChatDesc: 'Safihan oluranlowo AI lilefoofo lori gbogbo awon oju-ewe',
    progressSummary: 'Akopo Ilosiwaju Re', progressDesc: 'Iwo kan ti irin-ajo ScriptureHub re',
    exportData: 'Okeere Data Mi', exportDesc: 'Gba gbogbo ilosiwaju re bi faili JSON',
    downloadBtn: 'Gba Data Mi',
    resetSettings: 'Tun Eto Se', resetDesc: 'Mu gbogbo eto pada si awon iye aiyipada',
    resetBtn: 'Tun Se',
    clearData: 'Pa Gbogbo Data', clearDesc: 'Pa gbogbo ilosiwaju re run patapata.',
    clearBtn: 'Pa Gbogbo Re', reset: 'Tun Se',
    communityTitle: 'Odi Okuta Alaaye',
    communitySubtitle: 'Gbe igbagbo re, gba awon ami-eye, rin irin-ajo Ona Anabi.',
    stoneWall: 'Odi Okuta', treasureChest: 'Apoti Isura',
    prophetPath: 'Ona Anabi', easterEggs: 'Eyin Ojo Ajinde',
    carveStone: 'Gbe Okuta Re', carveBtn: 'Gbe Okuta Mi',
    carvedBtn: 'Okuta Ti Gbe!', wallTitle: 'Odi Iranti',
    stones: 'Awon Okuta', amen: 'Amin', amenDone: 'Amin',
    welcomeBack: 'Kaabo Pada', yourProgress: 'Ilosiwaju Re',
    beginner: 'Olubere', medium: 'Aarin', hard: 'Lile', scholar: 'Omowe',
    small: 'Kekere', large: 'Nla', extraLarge: 'Tobi Pupo',
  },

  swahili: {
    home: 'Nyumbani', bible: 'Biblia', quizzes: 'Maswali', askAI: 'Uliza AI',
    dashboard: 'Dashibodi', didYouKnow: 'Je, Ulijua', games: 'Michezo',
    community: 'Jamii', settings: 'Mipangilio', startStudying: 'Anza Kusoma',
    settingsTitle: 'Mipangilio', settingsSubtitle: 'Binafsisha uzoefu wako wa ScriptureHub',
    appearance: 'Mwonekano', reading: 'Kusoma', studyQuizzes: 'Masomo na Maswali',
    features: 'Vipengele', accountData: 'Akaunti na Data', about: 'Kuhusu',
    saveSettings: 'Hifadhi', saved: 'Imehifadhiwa!',
    darkMode: 'Hali ya Giza', darkModeDesc: 'Badilisha kati ya mandhari nyepesi na giza',
    accentColour: 'Rangi ya Msisitizo', accentColourDesc: 'Chagua rangi yako ya kibinafsi',
    fontSize: 'Ukubwa wa Fonti', fontSizeDesc: 'Rekebisha ukubwa wa maandishi ya kusoma',
    fontStyle: 'Mtindo wa Fonti', fontStyleDesc: 'Chagua fonti unayopendelea kusoma',
    compactMode: 'Hali ya Kompakt', compactModeDesc: 'Punguza nafasi kwa mpangilio mnene zaidi',
    animations: 'Mwendo wa Picha', animationsDesc: 'Wezesha mabadiliko laini',
    language: 'Lugha', languageDesc: 'Chagua lugha unayopendelea kuonyesha',
    defaultBible: 'Tafsiri ya Biblia ya Chaguo-msingi', defaultBibleDesc: 'Chagua tafsiri inayofunguka kwa chaguo-msingi',
    readingGoal: 'Lengo la Kusoma la Kila Siku', readingGoalDesc: 'Weka idadi ya sura unazotaka kusoma kila siku',
    chapter: 'sura', chapters: 'sura',
    verseOfDay: 'Aya ya Siku', verseOfDayDesc: 'Onyesha aya iliyoangaziwa kwenye dashibodi yako',
    autoPlay: 'Kucheza Kiotomatiki', autoPlayDesc: 'Cheza sauti kiotomatiki unapofungua sura',
    quizDifficulty: 'Ugumu wa Maswali', quizDifficultyDesc: 'Weka kiwango cha ugumu cha chaguo-msingi',
    showStreak: 'Onyesha Kihesabu cha Mfululizo', showStreakDesc: 'Onyesha mfululizo wako wa masomo ya kila siku',
    notifications: 'Vikumbusho vya Masomo', notificationsDesc: 'Pokea vikumbusho kudumisha mfululizo wako',
    soundEffects: 'Athari za Sauti', soundEffectsDesc: 'Cheza sauti kwenye majibu ya maswali',
    floatingChat: 'Mazungumzo ya AI Yanayoelea', floatingChatDesc: 'Onyesha msaidizi wa AI unaoelea kwenye kurasa zote',
    progressSummary: 'Muhtasari wa Maendeleo Yako', progressDesc: 'Muhtasari wa safari yako ya ScriptureHub',
    exportData: 'Hamisha Data Yangu', exportDesc: 'Pakua maendeleo yako yote kama faili ya JSON',
    downloadBtn: 'Pakua Data Yangu',
    resetSettings: 'Weka Upya Mipangilio', resetDesc: 'Rejesha mipangilio yote kwa thamani za chaguo-msingi',
    resetBtn: 'Weka Upya',
    clearData: 'Futa Data Zote', clearDesc: 'Futa maendeleo yako yote kabisa.',
    clearBtn: 'Futa Yote', reset: 'Weka Upya',
    communityTitle: 'Ukuta wa Mawe Ulio Hai',
    communitySubtitle: 'Chonga imani yako, pata beji, tembea Njia ya Nabii.',
    stoneWall: 'Ukuta wa Mawe', treasureChest: 'Sanduku la Hazina',
    prophetPath: 'Njia ya Nabii', easterEggs: 'Mayai ya Pasaka',
    carveStone: 'Chonga Jiwe Lako', carveBtn: 'Chonga Jiwe Langu',
    carvedBtn: 'Jiwe Limechongwa!', wallTitle: 'Ukuta wa Ukumbusho',
    stones: 'Mawe', amen: 'Amina', amenDone: 'Amina',
    welcomeBack: 'Karibu Tena', yourProgress: 'Maendeleo Yako',
    beginner: 'Mwanzo', medium: 'Kati', hard: 'Ngumu', scholar: 'Msomi',
    small: 'Ndogo', large: 'Kubwa', extraLarge: 'Kubwa Sana',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => loadJSON('scripturehub_language', 'english'))

  function changeLanguage(lang) {
    setLanguage(lang)
    saveJSON('scripturehub_language', lang)
    const settings = loadJSON('scripturehub_settings', {})
    settings.language = lang
    saveJSON('scripturehub_settings', settings)
  }

  const t = (key) => {
    const lang = TRANSLATIONS[language] || TRANSLATIONS.english
    return lang[key] || TRANSLATIONS.english[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, TRANSLATIONS }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}